from pathlib import Path
p=Path('campamento-equipo.html')
s=p.read_text(encoding='utf-8')
old='<div class="gold">Coronas de la compañía: <b id="gold">0</b></div><div class="gold">Tiradas D66 pendientes: <b id="pendingD66">0</b></div>'
new='''<div class="gold">Coronas de la compañía: <b id="gold">0</b></div><div class="armory-box"><h3>💰 Coronas y botín de enemigos</h3><p class="note"><b>Regla general:</b> enemigo de 1 Herida = 1D6 coronas · 2 Heridas = 1D6 + 1D4 · 3 Heridas = 2D6. Si la ficha del enemigo indica una recompensa distinta, prevalece la ficha y puedes anotarla manualmente aquí.</p><div class="item-row"><input id="manualGold" type="number" min="1" step="1" placeholder="Cantidad de coronas"><button onclick="addManualGold()">+ AÑADIR CORONAS</button><button onclick="removeManualGold()">− RESTAR CORONAS</button></div><div class="item-row" style="margin-top:10px"><select id="enemyWounds"><option value="1">Enemigo de 1 Herida · 1D6</option><option value="2">Enemigo de 2 Heridas · 1D6 + 1D4</option><option value="3">Enemigo de 3 Heridas · 2D6</option></select><input id="enemyCount" type="number" min="1" step="1" value="1" aria-label="Cantidad de enemigos"><button onclick="rollEnemyGold()">🎲 COBRAR BOTÍN DE ENEMIGOS</button></div><div id="goldStatus" class="shop-status"></div><p class="rule-note">Para enemigos de 4 o más Heridas, jefes o cualquier criatura con botín propio en su ficha, usa la recompensa indicada en esa ficha y añádela manualmente.</p></div><div class="gold">Tiradas D66 pendientes: <b id="pendingD66">0</b></div>'''
if old not in s:
    raise SystemExit('No se encontró el bloque de coronas')
s=s.replace(old,new,1)
old2='function die(n){return 1+Math.floor(Math.random()*n)}function dice(n,s){let t=0;for(let i=0;i<n;i++)t+=die(s);return t}'
new2='''function setGoldStatus(msg,type){const e=document.getElementById('goldStatus');if(!e)return;e.textContent=msg;e.className='shop-status '+(type||'')}function manualGoldValue(){const e=document.getElementById('manualGold');const n=Math.floor(Number(e?.value)||0);return n>0?n:0}function addManualGold(){const n=manualGoldValue();if(!n){setGoldStatus('Introduce una cantidad válida de coronas.','error');return}campaign.gold=(campaign.gold||0)+n;save();render();document.getElementById('manualGold').value='';setGoldStatus(`+${n} coronas añadidas manualmente. Total: ${campaign.gold}.`,'ok')}function removeManualGold(){const n=manualGoldValue();if(!n){setGoldStatus('Introduce una cantidad válida de coronas.','error');return}if(n>campaign.gold){setGoldStatus(`No puedes restar ${n}; la compañía solo tiene ${campaign.gold} coronas.`,'error');return}campaign.gold-=n;save();render();document.getElementById('manualGold').value='';setGoldStatus(`-${n} coronas. Total: ${campaign.gold}.`,'ok')}function die(n){return 1+Math.floor(Math.random()*n)}function dice(n,s){let t=0;for(let i=0;i<n;i++)t+=die(s);return t}function rollEnemyGold(){const w=Number(document.getElementById('enemyWounds')?.value)||1;const count=Math.max(1,Math.floor(Number(document.getElementById('enemyCount')?.value)||1));if(![1,2,3].includes(w))return;let rolls=[],total=0;for(let i=0;i<count;i++){let g=w===1?die(6):w===2?die(6)+die(4):dice(2,6);rolls.push(g);total+=g}campaign.gold=(campaign.gold||0)+total;save();render();const formula=w===1?'1D6':w===2?'1D6 + 1D4':'2D6';setGoldStatus(`${count} enemigo${count>1?'s':''} de ${w} Herida${w>1?'s':''}: ${formula} por enemigo → ${rolls.join(' + ')} = +${total} coronas. Total: ${campaign.gold}.`,'ok')}'''
if old2 not in s:
    raise SystemExit('No se encontró el bloque de dados')
s=s.replace(old2,new2,1)
p.write_text(s,encoding='utf-8')
print('campamento-equipo.html actualizado')
