(function(){
'use strict';
if(window.__cruzadaAmbientMusicLoaded)return;
window.__cruzadaAmbientMusicLoaded=true;

const DB_NAME='CruzadaAudioDB',STORE='audio',TRACK_ID='track:current';
const LS={enabled:'cruzadaMusicEnabled',volume:'cruzadaMusicVolume',position:'cruzadaMusicPosition',current:'cruzadaMusicCurrent'};
let audio=null,objectUrl=null,track=null;

function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function txDone(tx,db){return new Promise((resolve,reject)=>{tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)};tx.onabort=()=>{db.close();reject(tx.error||new Error('Transacción cancelada'))}})}
async function readStored(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),s=tx.objectStore(STORE),r=s.getAllKeys();r.onsuccess=()=>{const keys=r.result||[];if(!keys.length){db.close();resolve(null);return}const wanted=keys.includes(TRACK_ID)?TRACK_ID:keys[0],q=s.get(wanted);q.onsuccess=()=>{const f=q.result;db.close();resolve(f?{id:wanted,name:f.name||'Música',blob:f}:null)};q.onerror=()=>{db.close();reject(q.error)}};r.onerror=()=>{db.close();reject(r.error)}})}
async function clearStored(){const db=await openDb(),tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();await txDone(tx,db)}
async function putStored(file){const db=await openDb(),tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(file,TRACK_ID);await txDone(tx,db)}
async function replaceStored(file){const previous=await readStored();await clearStored();try{await putStored(file)}catch(err){if(previous&&previous.blob){try{await putStored(previous.blob)}catch(_){}}throw err}}

function enabled(){return localStorage.getItem(LS.enabled)!=='0'}
function volume(){const v=Number(localStorage.getItem(LS.volume));return Number.isFinite(v)?Math.max(0,Math.min(1,v)):0.22}
function introActive(){return !!document.getElementById('cruzadaIntro')}
function ensureAudio(){if(audio&&audio.isConnected)return audio;document.querySelectorAll('audio[data-cruzada-music],#cruzadaAmbientAudio').forEach(a=>{try{a.pause();a.remove()}catch(_){}});audio=document.createElement('audio');audio.id='cruzadaAmbientAudio';audio.dataset.cruzadaMusic='1';audio.loop=true;audio.preload='auto';audio.volume=volume();audio.style.display='none';document.body.appendChild(audio);audio.addEventListener('timeupdate',()=>{if(Number.isFinite(audio.currentTime))localStorage.setItem(LS.position,String(audio.currentTime))});audio.addEventListener('play',syncUi);audio.addEventListener('pause',syncUi);return audio}
function loadTrack(t,restore,forcePlay){track=t;if(!t){if(audio){audio.pause();audio.removeAttribute('src');audio.load()}syncUi();return}localStorage.setItem(LS.current,t.id);const a=ensureAudio();a.pause();a.removeAttribute('src');a.load();if(objectUrl){URL.revokeObjectURL(objectUrl);objectUrl=null}objectUrl=URL.createObjectURL(t.blob);a.src=objectUrl;a.volume=volume();a.addEventListener('loadedmetadata',function ready(){a.removeEventListener('loadedmetadata',ready);const saved=restore?Number(localStorage.getItem(LS.position)||0):0;if(saved>0&&saved<a.duration)a.currentTime=saved;else localStorage.setItem(LS.position,'0');if(forcePlay&&!introActive()){const p=a.play();if(p&&p.catch)p.catch(syncUi)}else if(enabled()&&!introActive()){const p=a.play();if(p&&p.catch)p.catch(syncUi)}syncUi()});a.load();renderList();syncUi()}
async function refresh(restore){try{const t=await readStored();loadTrack(t,restore,false)}catch(_){syncUi()}}

async function changeSong(file){if(!file)return;const name=file.name||'',type=(file.type||'').toLowerCase(),valid=type.startsWith('audio/')||/\.(mp3|m4a|mp4|aac|ogg|oga|opus|wav|wave|flac|webm)$/i.test(name)||(!type&&name.includes('.'));if(!valid){alert('Ese archivo no parece ser una canción compatible. Formatos admitidos: MP3, M4A, AAC, OGG, OPUS, WAV, FLAC, WEBM y otros audios reconocidos por Android.');return}const old=track;if(audio){audio.pause();audio.removeAttribute('src');audio.load()}try{await replaceStored(file);track={id:TRACK_ID,name:file.name||'Música',blob:file};localStorage.setItem(LS.current,TRACK_ID);localStorage.setItem(LS.position,'0');localStorage.setItem(LS.enabled,'1');loadTrack(track,false,true);alert('Canción cambiada correctamente.')}catch(e){track=old;if(old)loadTrack(old,true,false);const quota=e&&((e.name==='QuotaExceededError')||String(e.message||'').toLowerCase().includes('quota'));alert(quota?'No hay espacio suficiente para guardar esta canción. Prueba con un archivo de audio más pequeño.':'No se ha podido guardar la nueva canción. La anterior se ha restaurado.') }}
function openPicker(){let input=document.getElementById('cruzadaMusicFile');if(!input){input=document.createElement('input');input.id='cruzadaMusicFile';input.type='file';input.multiple=false;input.accept='audio/*,.mp3,.m4a,.mp4,.aac,.ogg,.oga,.opus,.wav,.wave,.flac,.webm';input.hidden=true;input.addEventListener('change',()=>{const f=input.files&&input.files[0];input.value='';if(f)changeSong(f)});document.body.appendChild(input)}input.click()}
function toggle(){if(!track){openPicker();return}const a=ensureAudio();if(a.paused){localStorage.setItem(LS.enabled,'1');if(!a.src)loadTrack(track,false,true);else{const p=a.play();if(p&&p.catch)p.catch(syncUi)}}else{a.pause();localStorage.setItem(LS.enabled,'0')}syncUi()}
async function removeCurrent(){if(!track||!confirm('¿Eliminar «'+track.name+'» de La Cruzada Eterna?'))return;try{if(audio){audio.pause();audio.removeAttribute('src');audio.load()}await clearStored();track=null;localStorage.removeItem(LS.current);localStorage.setItem(LS.position,'0');renderList();syncUi()}catch(_){alert('No se ha podido eliminar la canción.')}}
function setVolume(v){const n=Math.max(0,Math.min(100,Number(v)||0));localStorage.setItem(LS.volume,String(n/100));if(audio)audio.volume=n/100;const label=document.getElementById('cruzadaMusicVolumeValue');if(label)label.textContent=n+'%'}
function syncUi(){const btn=document.getElementById('cruzadaMusicToggle'),float=document.getElementById('cruzadaMusicFloat'),name=document.getElementById('cruzadaMusicName'),playing=!!(audio&&track&&!audio.paused);if(btn)btn.textContent=playing?'⏸ PAUSAR':'▶ REPRODUCIR';if(float){float.textContent=playing?'♫':'♪';float.title=track?(playing?'Pausar música':'Reproducir música'):'Seleccionar música';float.hidden=!track}if(name)name.textContent=track?track.name:'Ninguna música seleccionada'}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
function renderList(){const el=document.getElementById('cruzadaMusicList');if(!el)return;el.innerHTML=track?'<div style="display:flex;gap:6px;align-items:center"><button id="cruzadaMusicPlayCurrent" style="flex:1;text-align:left;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">▶ '+escapeHtml(track.name)+'</button><button id="cruzadaMusicDelete" title="Eliminar" style="width:auto;padding:8px 10px">×</button></div>':'<small style="color:#8f826e">Aún no has añadido ninguna canción.</small>';const p=document.getElementById('cruzadaMusicPlayCurrent'),d=document.getElementById('cruzadaMusicDelete');if(p)p.onclick=toggle;if(d)d.onclick=removeCurrent}
function addSettings(){const actions=document.querySelector('#menuDialog .settings-actions');if(!actions||document.getElementById('cruzadaMusicSettings'))return;const box=document.createElement('div');box.id='cruzadaMusicSettings';box.style.cssText='margin-top:14px;padding-top:14px;border-top:1px solid rgba(180,145,88,.28);display:grid;gap:8px';box.innerHTML='<b style="color:#d7bf8e;letter-spacing:1px">🎵 MÚSICA DE FONDO</b><small id="cruzadaMusicName" style="color:#b8aa91;overflow:hidden;text-overflow:ellipsis;white-space:nowrap"></small><button id="cruzadaMusicChoose">↻ CAMBIAR CANCIÓN</button><div id="cruzadaMusicList" style="display:grid;gap:5px;max-height:190px;overflow:auto"></div><button id="cruzadaMusicToggle">▶ REPRODUCIR</button><label style="display:flex;align-items:center;gap:10px;color:#c9b998;font-size:.82rem">VOLUMEN <input id="cruzadaMusicVolume" type="range" min="0" max="100" step="1" style="flex:1"><span id="cruzadaMusicVolumeValue"></span></label><small style="color:#8f826e;line-height:1.35">La app guarda una sola canción. Al cambiarla, primero libera el espacio de la anterior y después guarda la nueva.</small>';actions.insertBefore(box,actions.lastElementChild);document.getElementById('cruzadaMusicChoose').onclick=openPicker;document.getElementById('cruzadaMusicToggle').onclick=toggle;const range=document.getElementById('cruzadaMusicVolume');range.value=String(Math.round(volume()*100));range.oninput=e=>setVolume(e.target.value);document.getElementById('cruzadaMusicVolumeValue').textContent=range.value+'%';renderList();syncUi()}
function hookSettings(){if(typeof window.showMenuSettings!=='function'||window.showMenuSettings.__musicHook)return;const original=window.showMenuSettings;const wrapped=function(){original.apply(this,arguments);addSettings()};wrapped.__musicHook=true;window.showMenuSettings=wrapped}
function addFloat(){if(document.getElementById('cruzadaMusicFloat'))return;const b=document.createElement('button');b.id='cruzadaMusicFloat';b.type='button';b.hidden=true;b.setAttribute('aria-label','Música de fondo');b.style.cssText='position:fixed;right:14px;bottom:14px;z-index:99990;width:42px;height:42px;border-radius:50%;border:1px solid rgba(201,170,110,.7);background:rgba(18,14,10,.88);color:#e2c88f;font:700 20px Georgia,serif;box-shadow:0 3px 12px #000;backdrop-filter:blur(4px)';b.onclick=toggle;document.body.appendChild(b)}
function watchIntro(){if(!introActive()){if(enabled()&&track)toggle();return}const observer=new MutationObserver(()=>{if(!introActive()){observer.disconnect();setTimeout(()=>{if(enabled()&&track&&audio&&audio.paused){const p=audio.play();if(p&&p.catch)p.catch(syncUi)}},150)}});observer.observe(document.body,{childList:true})}
function applyRulesArt(){const el=document.querySelector('.gothic-tile.rules .tile-art');if(!el)return;el.textContent='';el.style.backgroundImage="url('assets/file_0000000081008210a533bb03b5a83b36.png?v=1')";el.style.backgroundSize='cover';el.style.backgroundPosition='center 48%';el.style.backgroundRepeat='no-repeat'}
function applyHeroesArt(){const el=document.querySelector('.gothic-tile.heroes .tile-art');if(!el)return;el.textContent='';el.style.backgroundImage="url('assets/file_000000000cf08243b58d929592a6fae7.png?v=1')";el.style.backgroundSize='cover';el.style.backgroundPosition='center 42%';el.style.backgroundRepeat='no-repeat'}
function applyEquipmentArt(){const el=document.querySelector('.gothic-tile.equipment .tile-art');if(!el)return;el.textContent='';el.style.backgroundImage="url('assets/file_0000000077948210a93709f56a4ef79c.png?v=1')";el.style.backgroundSize='cover';el.style.backgroundPosition='center 48%';el.style.backgroundRepeat='no-repeat'}
function applyMagicArt(){const el=document.querySelector('.gothic-tile.magic .tile-art');if(!el)return;el.textContent='';el.style.backgroundImage="url('assets/file_00000000ff48821091944249ca3078fd.png?v=1')";el.style.backgroundSize='cover';el.style.backgroundPosition='center 47%';el.style.backgroundRepeat='no-repeat'}
function init(){ensureAudio();addFloat();hookSettings();applyRulesArt();applyHeroesArt();applyEquipmentArt();applyMagicArt();refresh(true).then(watchIntro);setInterval(hookSettings,1000);window.addEventListener('pagehide',()=>{if(audio&&Number.isFinite(audio.currentTime))localStorage.setItem(LS.position,String(audio.currentTime))})}
window.cruzadaMusic={select:openPicker,toggle,setVolume};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
