(function(){
'use strict';
const DB_NAME='CruzadaAudioDB',STORE='audio',KEY='bgm';
const LS={enabled:'cruzadaMusicEnabled',volume:'cruzadaMusicVolume',position:'cruzadaMusicPosition',name:'cruzadaMusicName'};
let audio=null,objectUrl=null,selectedName=localStorage.getItem(LS.name)||'',hasTrack=false;
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function getTrack(){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(KEY);r.onsuccess=()=>{d.close();resolve(r.result||null)};r.onerror=()=>{d.close();reject(r.error)}})}
async function saveTrack(file){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(file,KEY);tx.oncomplete=()=>{d.close();resolve()};tx.onerror=()=>{d.close();reject(tx.error)}})}
function enabled(){return localStorage.getItem(LS.enabled)!=='0'}
function volume(){const v=Number(localStorage.getItem(LS.volume));return Number.isFinite(v)?Math.max(0,Math.min(1,v)):0.22}
function ensureAudio(){if(audio)return audio;audio=document.createElement('audio');audio.id='cruzadaAmbientAudio';audio.loop=true;audio.preload='auto';audio.volume=volume();audio.style.display='none';document.body.appendChild(audio);audio.addEventListener('timeupdate',()=>{if(Number.isFinite(audio.currentTime))localStorage.setItem(LS.position,String(audio.currentTime))});audio.addEventListener('play',syncUi);audio.addEventListener('pause',syncUi);return audio}
function introActive(){return !!document.getElementById('cruzadaIntro')}
function playWhenReady(){if(!audio||!hasTrack||!enabled()||introActive())return;const p=audio.play();if(p&&p.catch)p.catch(()=>syncUi())}
function setSource(blob,name){const a=ensureAudio();if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(blob);a.src=objectUrl;selectedName=name||selectedName||'Música seleccionada';hasTrack=true;a.volume=volume();a.addEventListener('loadedmetadata',function restore(){a.removeEventListener('loadedmetadata',restore);const saved=Number(localStorage.getItem(LS.position)||0);if(Number.isFinite(saved)&&saved>0&&saved<a.duration)a.currentTime=saved;playWhenReady();syncUi()});a.load();syncUi()}
async function loadStored(){try{const blob=await getTrack();if(blob){setSource(blob,selectedName||blob.name||'Música seleccionada')}else syncUi()}catch(e){syncUi()}}
async function selectFile(file){if(!file)return;try{await saveTrack(file);selectedName=file.name||'Música seleccionada';localStorage.setItem(LS.name,selectedName);localStorage.setItem(LS.position,'0');localStorage.setItem(LS.enabled,'1');if(navigator.storage&&navigator.storage.persist)navigator.storage.persist().catch(()=>{});setSource(file,selectedName)}catch(e){alert('No se ha podido guardar la música en este dispositivo.')}}
function toggle(){if(!hasTrack){openPicker();return}if(!audio)return;if(audio.paused){localStorage.setItem(LS.enabled,'1');playWhenReady()}else{audio.pause();localStorage.setItem(LS.enabled,'0')}syncUi()}
function openPicker(){let input=document.getElementById('cruzadaMusicFile');if(!input){input=document.createElement('input');input.id='cruzadaMusicFile';input.type='file';input.accept='audio/*,.mp3,.m4a,.ogg,.wav,.flac';input.hidden=true;input.addEventListener('change',()=>{const f=input.files&&input.files[0];if(f)selectFile(f);input.value=''});document.body.appendChild(input)}input.click()}
function setVolume(v){const n=Math.max(0,Math.min(100,Number(v)||0));localStorage.setItem(LS.volume,String(n/100));if(audio)audio.volume=n/100;const label=document.getElementById('cruzadaMusicVolumeValue');if(label)label.textContent=n+'%'}
function syncUi(){const btn=document.getElementById('cruzadaMusicToggle'),float=document.getElementById('cruzadaMusicFloat'),name=document.getElementById('cruzadaMusicName');const playing=!!(audio&&hasTrack&&!audio.paused);if(btn)btn.textContent=playing?'⏸ PAUSAR':'▶ REPRODUCIR';if(float){float.textContent=playing?'♫':'♪';float.title=hasTrack?(playing?'Pausar música':'Reproducir música'):'Seleccionar música';float.hidden=!hasTrack}if(name)name.textContent=hasTrack?(selectedName||'Música seleccionada'):'Ninguna música seleccionada'}
function addSettings(){const actions=document.querySelector('#menuDialog .settings-actions');if(!actions||document.getElementById('cruzadaMusicSettings'))return;const box=document.createElement('div');box.id='cruzadaMusicSettings';box.style.cssText='margin-top:14px;padding-top:14px;border-top:1px solid rgba(180,145,88,.28);display:grid;gap:8px';box.innerHTML='<b style="color:#d7bf8e;letter-spacing:1px">🎵 MÚSICA DE FONDO</b><small id="cruzadaMusicName" style="color:#b8aa91;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">Ninguna música seleccionada</small><button id="cruzadaMusicChoose">♫ SELECCIONAR MÚSICA</button><button id="cruzadaMusicToggle">▶ REPRODUCIR</button><label style="display:flex;align-items:center;gap:10px;color:#c9b998;font-size:.82rem">VOLUMEN <input id="cruzadaMusicVolume" type="range" min="0" max="100" step="1" style="flex:1"><span id="cruzadaMusicVolumeValue"></span></label><small style="color:#8f826e;line-height:1.35">La canción se guarda solo en este dispositivo y no se sube a Internet.</small>';
actions.insertBefore(box,actions.lastElementChild);document.getElementById('cruzadaMusicChoose').onclick=openPicker;document.getElementById('cruzadaMusicToggle').onclick=toggle;const range=document.getElementById('cruzadaMusicVolume');range.value=String(Math.round(volume()*100));range.oninput=e=>setVolume(e.target.value);document.getElementById('cruzadaMusicVolumeValue').textContent=range.value+'%';syncUi()}
function hookSettings(){if(typeof window.showMenuSettings!=='function'||window.showMenuSettings.__musicHook)return;const original=window.showMenuSettings;const wrapped=function(){original.apply(this,arguments);addSettings()};wrapped.__musicHook=true;window.showMenuSettings=wrapped}
function addFloat(){if(document.getElementById('cruzadaMusicFloat'))return;const b=document.createElement('button');b.id='cruzadaMusicFloat';b.type='button';b.hidden=true;b.setAttribute('aria-label','Música de fondo');b.style.cssText='position:fixed;right:14px;bottom:14px;z-index:99990;width:42px;height:42px;border-radius:50%;border:1px solid rgba(201,170,110,.7);background:rgba(18,14,10,.88);color:#e2c88f;font:700 20px Georgia,serif;box-shadow:0 3px 12px #000;backdrop-filter:blur(4px)';b.onclick=toggle;document.body.appendChild(b)}
function watchIntro(){if(!introActive()){playWhenReady();return}const observer=new MutationObserver(()=>{if(!introActive()){observer.disconnect();setTimeout(playWhenReady,150)}});observer.observe(document.body,{childList:true})}
function init(){ensureAudio();addFloat();hookSettings();loadStored().then(watchIntro);setInterval(hookSettings,1000);window.addEventListener('pagehide',()=>{if(audio&&Number.isFinite(audio.currentTime))localStorage.setItem(LS.position,String(audio.currentTime))})}
window.cruzadaMusic={select:openPicker,toggle,setVolume};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
