(function(){
'use strict';
const DB_NAME='CruzadaAudioDB',STORE='audio';
const LS={enabled:'cruzadaMusicEnabled',volume:'cruzadaMusicVolume',position:'cruzadaMusicPosition',current:'cruzadaMusicCurrent'};
let audio=null,objectUrl=null,tracks=[],currentId=localStorage.getItem(LS.current)||'';
function stopStrayAudio(){document.querySelectorAll('audio[data-cruzada-music],#cruzadaAmbientAudio').forEach(a=>{try{a.pause();a.removeAttribute('src');a.load();a.remove()}catch(e){}})}
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function allTracks(){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readonly'),s=tx.objectStore(STORE),r=s.getAllKeys();r.onsuccess=()=>{const keys=r.result||[],out=[];if(!keys.length){d.close();resolve([]);return}let pending=keys.length;keys.forEach(k=>{const q=s.get(k);q.onsuccess=()=>{const f=q.result;if(f)out.push({id:String(k),name:f.name||String(k),blob:f});if(!--pending){d.close();resolve(out)}};q.onerror=()=>{if(!--pending){d.close();resolve(out)}}})};r.onerror=()=>{d.close();reject(r.error)}})}
async function saveFiles(files){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readwrite'),s=tx.objectStore(STORE),ids=[];files.forEach(f=>{const id='track:'+Date.now()+':'+Math.random().toString(36).slice(2);ids.push(id);s.put(f,id)});tx.oncomplete=()=>{d.close();resolve(ids)};tx.onerror=()=>{d.close();reject(tx.error)}})}
async function removeTrack(id){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=()=>{d.close();resolve()};tx.onerror=()=>{d.close();reject(tx.error)}})}
function enabled(){return localStorage.getItem(LS.enabled)!=='0'}
function volume(){const v=Number(localStorage.getItem(LS.volume));return Number.isFinite(v)?Math.max(0,Math.min(1,v)):0.22}
function current(){return tracks.find(t=>t.id===currentId)||tracks[0]||null}
function ensureAudio(){if(audio&&audio.isConnected)return audio;audio=document.createElement('audio');audio.id='cruzadaAmbientAudio';audio.dataset.cruzadaMusic='1';audio.loop=true;audio.preload='auto';audio.volume=volume();audio.style.display='none';document.body.appendChild(audio);audio.addEventListener('timeupdate',()=>{if(Number.isFinite(audio.currentTime))localStorage.setItem(LS.position,String(audio.currentTime))});audio.addEventListener('play',syncUi);audio.addEventListener('pause',syncUi);return audio}
function introActive(){return !!document.getElementById('cruzadaIntro')}
function playWhenReady(){if(!audio||!current()||!enabled()||introActive())return;const p=audio.play();if(p&&p.catch)p.catch(syncUi)}
function setSource(track,restore,forcePlay){if(!track){if(audio){audio.pause();audio.removeAttribute('src');audio.load()}syncUi();return}currentId=track.id;localStorage.setItem(LS.current,currentId);const a=ensureAudio();a.pause();try{a.currentTime=0}catch(e){}a.removeAttribute('src');a.load();if(objectUrl){URL.revokeObjectURL(objectUrl);objectUrl=null}objectUrl=URL.createObjectURL(track.blob);a.src=objectUrl;a.volume=volume();a.addEventListener('loadedmetadata',function ready(){a.removeEventListener('loadedmetadata',ready);const saved=restore?Number(localStorage.getItem(LS.position)||0):0;if(saved>0&&saved<a.duration)a.currentTime=saved;else localStorage.setItem(LS.position,'0');if(!forcePlay)playWhenReady();syncUi()});a.load();if(forcePlay&&!introActive()){const p=a.play();if(p&&p.catch)p.catch(()=>syncUi())}renderList();syncUi()}
async function refresh(restore){try{tracks=await allTracks();if(currentId&&!tracks.some(t=>t.id===currentId))currentId='';if(!currentId&&tracks[0])currentId=tracks[0].id;const t=current();if(t)setSource(t,restore,false);else setSource(null,false,false)}catch(e){syncUi()}}
async function addFiles(list){const files=Array.from(list||[]).filter(f=>f&&(f.type.startsWith('audio/')||/\.(mp3|m4a|ogg|wav|flac)$/i.test(f.name||'')));if(!files.length)return;try{if(audio){audio.pause();audio.removeAttribute('src');audio.load()}const ids=await saveFiles(files);if(navigator.storage&&navigator.storage.persist)navigator.storage.persist().catch(()=>{});tracks=await allTracks();if(ids.length){currentId=ids[0];localStorage.setItem(LS.current,currentId);localStorage.setItem(LS.position,'0');localStorage.setItem(LS.enabled,'1');const t=tracks.find(x=>x.id===currentId);if(t)setSource(t,false,true)}else syncUi()}catch(e){alert('No se ha podido guardar la música en este dispositivo.')}}
function toggle(){if(!current()){openPicker();return}if(audio.paused){localStorage.setItem(LS.enabled,'1');playWhenReady()}else{audio.pause();localStorage.setItem(LS.enabled,'0')}syncUi()}
function openPicker(){let input=document.getElementById('cruzadaMusicFile');if(!input){input=document.createElement('input');input.id='cruzadaMusicFile';input.type='file';input.multiple=true;input.accept='audio/*,.mp3,.m4a,.ogg,.wav,.flac';input.hidden=true;input.addEventListener('change',()=>{addFiles(input.files);input.value=''});document.body.appendChild(input)}input.click()}
function choose(id){const t=tracks.find(x=>x.id===id);if(!t)return;localStorage.setItem(LS.position,'0');localStorage.setItem(LS.enabled,'1');setSource(t,false,true)}
async function del(id){const t=tracks.find(x=>x.id===id);if(!t||!confirm('¿Eliminar «'+t.name+'» de la biblioteca de La Cruzada Eterna?'))return;const wasCurrent=id===currentId;if(wasCurrent&&audio){audio.pause();audio.removeAttribute('src');audio.load()}await removeTrack(id);tracks=tracks.filter(x=>x.id!==id);if(wasCurrent){currentId=tracks[0]?.id||'';if(currentId)localStorage.setItem(LS.current,currentId);else localStorage.removeItem(LS.current);localStorage.setItem(LS.position,'0');if(currentId){const next=tracks.find(x=>x.id===currentId);if(next)setSource(next,false,false)}else setSource(null,false,false)}renderList();syncUi()}
function setVolume(v){const n=Math.max(0,Math.min(100,Number(v)||0));localStorage.setItem(LS.volume,String(n/100));if(audio)audio.volume=n/100;const label=document.getElementById('cruzadaMusicVolumeValue');if(label)label.textContent=n+'%'}
function syncUi(){const btn=document.getElementById('cruzadaMusicToggle'),float=document.getElementById('cruzadaMusicFloat'),name=document.getElementById('cruzadaMusicName'),t=current(),playing=!!(audio&&t&&!audio.paused);if(btn)btn.textContent=playing?'⏸ PAUSAR':'▶ REPRODUCIR';if(float){float.textContent=playing?'♫':'♪';float.title=t?(playing?'Pausar música':'Reproducir música'):'Seleccionar música';float.hidden=!t}if(name)name.textContent=t?t.name:'Ninguna música seleccionada'}
function renderList(){const el=document.getElementById('cruzadaMusicList');if(!el)return;el.innerHTML=tracks.length?tracks.map(t=>'<div style="display:flex;gap:6px;align-items:center"><button data-play="'+t.id+'" style="flex:1;text-align:left;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+(t.id===currentId?'▶ ':'♫ ')+escapeHtml(t.name)+'</button><button data-del="'+t.id+'" title="Eliminar" style="width:auto;padding:8px 10px">×</button></div>').join(''):'<small style="color:#8f826e">Aún no has añadido canciones.</small>';el.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>choose(b.dataset.play));el.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>del(b.dataset.del))}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function addSettings(){const actions=document.querySelector('#menuDialog .settings-actions');if(!actions||document.getElementById('cruzadaMusicSettings'))return;const box=document.createElement('div');box.id='cruzadaMusicSettings';box.style.cssText='margin-top:14px;padding-top:14px;border-top:1px solid rgba(180,145,88,.28);display:grid;gap:8px';box.innerHTML='<b style="color:#d7bf8e;letter-spacing:1px">🎵 MÚSICA DE FONDO</b><small id="cruzadaMusicName" style="color:#b8aa91;overflow:hidden;text-overflow:ellipsis;white-space:nowrap"></small><button id="cruzadaMusicChoose">＋ AÑADIR CANCIONES</button><div id="cruzadaMusicList" style="display:grid;gap:5px;max-height:190px;overflow:auto"></div><button id="cruzadaMusicToggle">▶ REPRODUCIR</button><label style="display:flex;align-items:center;gap:10px;color:#c9b998;font-size:.82rem">VOLUMEN <input id="cruzadaMusicVolume" type="range" min="0" max="100" step="1" style="flex:1"><span id="cruzadaMusicVolumeValue"></span></label><small style="color:#8f826e;line-height:1.35">Al elegir otra canción, la anterior se detiene antes de empezar la nueva. Los archivos permanecen solo en este dispositivo.</small>';actions.insertBefore(box,actions.lastElementChild);document.getElementById('cruzadaMusicChoose').onclick=openPicker;document.getElementById('cruzadaMusicToggle').onclick=toggle;const range=document.getElementById('cruzadaMusicVolume');range.value=String(Math.round(volume()*100));range.oninput=e=>setVolume(e.target.value);document.getElementById('cruzadaMusicVolumeValue').textContent=range.value+'%';renderList();syncUi()}
function hookSettings(){if(typeof window.showMenuSettings!=='function'||window.showMenuSettings.__musicHook)return;const original=window.showMenuSettings;const wrapped=function(){original.apply(this,arguments);addSettings()};wrapped.__musicHook=true;window.showMenuSettings=wrapped}
function addFloat(){if(document.getElementById('cruzadaMusicFloat'))return;const b=document.createElement('button');b.id='cruzadaMusicFloat';b.type='button';b.hidden=true;b.setAttribute('aria-label','Música de fondo');b.style.cssText='position:fixed;right:14px;bottom:14px;z-index:99990;width:42px;height:42px;border-radius:50%;border:1px solid rgba(201,170,110,.7);background:rgba(18,14,10,.88);color:#e2c88f;font:700 20px Georgia,serif;box-shadow:0 3px 12px #000;backdrop-filter:blur(4px)';b.onclick=toggle;document.body.appendChild(b)}
function watchIntro(){if(!introActive()){playWhenReady();return}const observer=new MutationObserver(()=>{if(!introActive()){observer.disconnect();setTimeout(playWhenReady,150)}});observer.observe(document.body,{childList:true})}
function init(){stopStrayAudio();ensureAudio();addFloat();hookSettings();refresh(true).then(watchIntro);setInterval(hookSettings,1000);window.addEventListener('pagehide',()=>{if(audio&&Number.isFinite(audio.currentTime))localStorage.setItem(LS.position,String(audio.currentTime))})}
window.cruzadaMusic={select:openPicker,toggle,setVolume};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
