(function(){
const KEY='cruzadaMarcadores_mision5_html',POTIONS=['Poción Curativa Menor','Poción Curativa Mayor','Poción de Fuerza','Poción de Fuerza de Gigante','Poción de Resistencia'];
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function campaign(){try{return JSON.parse(localStorage.getItem('cruzadaCampaign')||'null')}catch(e){return null}}
function markerState(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}}
function saveState(state){localStorage.setItem(KEY,JSON.stringify(state))}
function addInventory(item){const c=campaign();if(!c)return;c.inventory=Array.isArray(c.inventory)?c.inventory:[];c.inventory.push(item);localStorage.setItem('cruzadaCampaign',JSON.stringify(c))}
function controls(index){const heroes=campaign()?.heroes||[],state=markerState(),done=state[index];if(done)return '<div class="marker-result"><b>✓ RESUELTO</b><small>'+esc(done.hero)+' · '+esc(done.result)+'</small></div>';return '<div class="marker-action"><select id="mission5MarkerHero'+index+'">'+heroes.map(h=>'<option value="'+esc(h.name)+'">'+esc(h.name)+'</option>').join('')+'</select><button type="button" onclick="resolveMission5Marker('+index+')">RESOLVER MARCADOR</button></div>'}
function render(){for(let i=1;i<=6;i++){const box=document.querySelector('[data-mission5-marker="'+i+'"]');if(box)box.innerHTML=controls(i)}}
function successEffect(index,hero){if(index===1)window.addMissionTemporaryEffect?.({hero,item:'Inscripción de Sigmar',label:'Bendición de Sigmar',detail:'Una vez por turno puede repetir una tirada para impactar'});if(index===2)window.addMissionTemporaryEffect?.({hero,item:'Estatua de Morr',label:'Protección de Morr',detail:'Ignora la primera Herida sufrida durante el resto del combate',actionLabel:'APLICAR AL RECIBIR HERIDA'});if(index===3)window.addMissionTemporaryEffect?.({hero,item:'Vitrales Sagrados',label:'+1 Salvación',detail:'Duración: hasta el final de la batalla',stat:'SALV',bonus:1});if(index===5)window.addMissionTemporaryEffect?.({hero,item:'Escrituras del Exorcismo',label:'Odio contra Varkhos',detail:'Repite las tiradas para impactar fallidas contra Varkhos'});if(index===6){window.healMissionHeroFullyByName?.(hero);window.addMissionTemporaryEffect?.({hero,item:'Tumba del Mártir',label:'+1 Liderazgo',detail:'Duración: hasta el final de la batalla',stat:'L',bonus:1})}}
window.resolveMission5Marker=function(index){const state=markerState();if(state[index])return;const select=document.getElementById('mission5MarkerHero'+index),hero=select?.value;if(!hero)return;let result='',success=true;if(index===4){const roll=1+Math.floor(Math.random()*6),item=roll<=3?'Pergamino Sagrado':POTIONS[Math.floor(Math.random()*POTIONS.length)];addInventory(item);result='1D6: '+roll+' · '+item+' añadido al inventario'}else{const test=window.rollMissionLeadership?.(hero);if(!test)return;success=test.success;if(success){successEffect(index,hero);const rewards={1:'Bendición de Sigmar',2:'Ignora la primera Herida',3:'+1 Salvación',5:'Odio contra Varkhos',6:'Recupera todas las Heridas y obtiene +1 Liderazgo'};result='Liderazgo '+test.dice.join('+')+' = '+test.total+' contra '+test.target+' · Éxito · '+rewards[index]}else{result='Liderazgo '+test.dice.join('+')+' = '+test.total+' contra '+test.target+' · Fallo';if(index===6){window.addMissionTemporaryEffect?.({hero,item:'Tumba del Mártir',label:'Impacto de Fuerza 4 pendiente',detail:'Resuelve el impacto y después finaliza este aviso',actionLabel:'IMPACTO RESUELTO'});result+=' · Debe resolver un impacto de Fuerza 4'}}}state[index]={hero,result,success};saveState(state);render();alert(result)}
const heading=Array.from(document.querySelectorAll('h2')).find(x=>x.textContent.trim()==='Marcadores de exploración'),boxes=heading?.parentElement?.querySelectorAll('.grid > .box')||[];boxes.forEach((box,i)=>{const control=document.createElement('div');control.className='mission5-marker-control';control.dataset.mission5Marker=String(i+1);box.appendChild(control)});render();
const originalReset=window.resetTest;if(typeof originalReset==='function')window.resetTest=function(){localStorage.removeItem(KEY);localStorage.removeItem('cruzadaAltarSigmar_mision5_html');localStorage.removeItem('cruzadaEfectos_mision5_html');localStorage.removeItem('cruzadaHeridas_mision5_html');localStorage.removeItem('cruzadaConsumidos_mision5_html');originalReset()};
if(!document.getElementById('mission5-marker-style')){const style=document.createElement('style');style.id='mission5-marker-style';style.textContent='.mission5-marker-control{margin-top:9px;padding-top:8px;border-top:1px solid rgba(192,147,80,.35)}.marker-action select{width:100%;padding:7px;background:#100d0c;color:#eadfc9;border:1px solid #6e5337;border-radius:6px}.marker-action button{width:100%;margin:7px 0 0;font-size:.7rem;padding:8px}.marker-result{color:#dfbd77}.marker-result small{display:block;margin-top:4px;color:#d8c8ae}';document.head.appendChild(style)}
})();
