(function(){
const KEY='cruzadaVarkhos_mision5_html';
function mission4(){try{return JSON.parse(localStorage.getItem('cruzadaMission4')||'{}')}catch(e){return{}}}
function seals(){const m=mission4();return{blood:!!m.blood,bone:!!m.bone,shadow:!!m.shadow}}
function initialState(){const s=seals(),max=6+(s.blood?0:1),destroyed=!!document.getElementById('chalice')?.checked;return{current:max,max,chaliceCurrent:destroyed?0:3,chaliceDestroyed:destroyed,phase2:destroyed,lastRegen:null}}
function getState(){let value;try{value=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){}const fresh=initialState();if(!value)value=fresh;value.max=fresh.max;value.current=Math.max(0,Math.min(value.max,Number(value.current)??value.max));const chalice=Number(value.chaliceCurrent);value.chaliceCurrent=Number.isFinite(chalice)?Math.max(0,Math.min(3,chalice)):(value.chaliceDestroyed?0:3);value.chaliceDestroyed=!!value.chaliceDestroyed||value.chaliceCurrent===0;if(value.chaliceDestroyed)value.chaliceCurrent=0;value.phase2=!!value.phase2||value.chaliceDestroyed||value.current<=3;return value}
function saveState(value){localStorage.setItem(KEY,JSON.stringify(value))}
function syncMissionCheckbox(id,checked){const input=document.getElementById(id);if(!input||input.checked===checked)return;input.checked=checked;input.dispatchEvent(new Event('change',{bubbles:true}))}
function sealLine(destroyed,yes,no){return '<div class="varkhos-seal '+(destroyed?'destroyed':'active')+'">'+(destroyed?'✓ '+yes:'⚠ '+no)+'</div>'}
function aiAction(roll,phase2){if(roll<=2)return{title:'Ataque del Señor Vampiro',text:'Carga al héroe más cercano si puede. Si ya está en combate, realiza sus '+(phase2?4:3)+' Ataques con la Espada Carmesí a Fuerza '+(phase2?6:5)+'.'};if(roll<=4)return{title:'Poder de la Sangre Negra',text:phase2?'Utiliza una capacidad mágica disponible con 3 Dados de Magia. No puede lanzar Mirada Hipnótica.':'Utiliza una capacidad mágica disponible con 3 Dados de Magia. Mirada Hipnótica está disponible.'};if(roll===5)return{title:'Dominio de Varkhos',text:phase2?'Activa su capacidad de Segunda Fase. Recuerda: +1 Fuerza, +1 Ataque y Terror.':'Activa su capacidad de Primera Fase. Conserva toda su magia y prioriza al héroe más débil.'};return{title:'Furia del Señor de la Sangre',text:phase2?'Desata su acción especial de Segunda Fase con FUE 6 y 4 Ataques. Mirada Hipnótica permanece desactivada.':'Desata su acción especial de Primera Fase con FUE 5, 3 Ataques y toda su magia disponible.'}}
function renderAI(state,dead){const history=Array.isArray(state.aiHistory)?state.aiHistory:[];return '<div class="varkhos-ai"><b>🎲 INTELIGENCIA DE VARKHOS · 1D6</b><button type="button" onclick="rollVarkhosAI()" '+(dead?'disabled':'')+'>TIRAR ACCIÓN DE IA</button>'+(history.length?'<div class="varkhos-ai-current"><strong>'+history[0].roll+' · '+history[0].title+'</strong><span>'+history[0].text+'</span><small>'+history[0].phase+'</small></div><details><summary>Historial de acciones ('+history.length+')</summary>'+history.map(x=>'<p><b>'+x.roll+' · '+x.title+'</b><br>'+x.text+'<small>'+x.phase+'</small></p>').join('')+'</details>':'<small>Aún no se ha realizado ninguna tirada de IA.</small>')+'</div>'}
function renderChalice(state,dead){const destroyed=state.chaliceDestroyed;return '<div class="varkhos-chalice '+(destroyed?'chalice-broken':'')+'"><div class="chalice-head"><b>◆ CÁLIZ DE SANGRE NEGRA</b><strong>'+state.chaliceCurrent+' / 3 HERIDAS</strong></div><span>RES 5 · Salvación especial 5+</span><small>Solo puede dañarse con magia, armas mágicas, ataques flamígeros o la Estaca Bendita.</small><div class="chalice-wounds"><button type="button" onclick="changeVarkhosChaliceWounds(-1)" '+(destroyed?'disabled':'')+'>− HERIDA AL CÁLIZ</button><button type="button" onclick="changeVarkhosChaliceWounds(1)" '+(state.chaliceCurrent>=3?'disabled':'')+'>+ HERIDA AL CÁLIZ</button></div>'+(destroyed?'<div class="chalice-impact">🔥 DESTRUIDO · Todos los No Muertos sufren un impacto de Fuerza 4.</div>':'<small>Mientras siga intacto, Varkhos conserva Regeneración 6+ y su recuperación.</small>')+'<div class="varkhos-recovery"><button type="button" onclick="rollVarkhosRegeneration()" '+(destroyed||dead||state.current>=state.max?'disabled':'')+'>TIRAR REGENERACIÓN 6+</button><button type="button" onclick="healVarkhosAtMasterTurn()" '+(destroyed||dead||state.current>=state.max?'disabled':'')+'>INICIO TURNO DEL MÁSTER · +1 H</button></div>'+(state.lastRegen?'<small class="varkhos-last">Última regeneración: '+state.lastRegen+'</small>':'')+'</div>'}
function render(){const box=document.getElementById('varkhosCombatControl');if(!box)return;const state=getState(),s=seals(),phase2=state.phase2,dead=state.current<=0;saveState(state);syncMissionCheckbox('varkhos',dead);syncMissionCheckbox('chalice',state.chaliceDestroyed);box.innerHTML='<div class="varkhos-head"><div><small>JEFE FINAL</small><b>VARKHOS</b></div><strong>'+state.current+' / '+state.max+' HERIDAS</strong></div><div class="varkhos-wounds"><button type="button" onclick="changeVarkhosWounds(-1)" '+(dead?'disabled':'')+'>− HERIDA</button><button type="button" onclick="changeVarkhosWounds(1)" '+(state.current>=state.max?'disabled':'')+'>+ HERIDA</button></div><div class="varkhos-phase '+(phase2?'phase-two':'')+'"><b>'+(phase2?'SEGUNDA FASE · LA BESTIA CARMESÍ':'PRIMERA FASE · EL NOBLE INMORTAL')+'</b><span>FUE '+(phase2?6:5)+' · ATQ '+(phase2?4:3)+' · R 5 · Salvación 4+</span><small>'+(phase2?'Provoca Terror · Mirada Hipnótica desactivada · +1 FUE y +1 ATQ':'Magia completa · Mirada Hipnótica disponible')+'</small></div>'+renderAI(state,dead)+renderChalice(state,dead)+'<div class="varkhos-seals"><b>CONSECUENCIAS DE LOS SELLOS</b>'+sealLine(s.blood,'Sello de Sangre destruido','Sello de Sangre activo: +1 Herida máxima')+sealLine(s.bone,'Sello de Hueso destruido','Sello de Hueso activo: coloca 2 Esqueletos adicionales')+sealLine(s.shadow,'Sello de las Sombras destruido','Sello de las Sombras activo: cobertura ligera permanente')+'</div>'+(dead?'<div class="varkhos-defeated">☠ VARKHOS HA SIDO DERROTADO</div>':'')}
window.changeVarkhosWounds=function(delta){const state=getState();state.current=Math.max(0,Math.min(state.max,state.current+delta));if(state.current<=3)state.phase2=true;saveState(state);render()}
window.setVarkhosChalice=function(destroyed){const state=getState();state.chaliceDestroyed=!!destroyed;state.chaliceCurrent=destroyed?0:3;if(destroyed)state.phase2=true;saveState(state);render()}
window.changeVarkhosChaliceWounds=function(delta){const state=getState(),wasDestroyed=state.chaliceDestroyed;state.chaliceCurrent=Math.max(0,Math.min(3,state.chaliceCurrent+delta));state.chaliceDestroyed=state.chaliceCurrent===0;if(state.chaliceDestroyed)state.phase2=true;saveState(state);render();if(!wasDestroyed&&state.chaliceDestroyed)alert('El Cáliz ha sido destruido. Varkhos entra en Segunda Fase, pierde Regeneración y recuperación, y todos los No Muertos sufren un impacto de Fuerza 4.')}
window.rollVarkhosRegeneration=function(){const state=getState();if(state.chaliceDestroyed||state.current<=0||state.current>=state.max)return;const roll=1+Math.floor(Math.random()*6);if(roll===6)state.current++;state.lastRegen=roll+(roll===6?' · Éxito, recupera 1 Herida':' · Fallo');saveState(state);render();alert('Regeneración de Varkhos: '+state.lastRegen+'.')}
window.healVarkhosAtMasterTurn=function(){const state=getState();if(state.chaliceDestroyed||state.current<=0||state.current>=state.max)return;state.current++;saveState(state);render()}
window.rollVarkhosAI=function(){const state=getState();if(state.current<=0)return;const roll=1+Math.floor(Math.random()*6),action=aiAction(roll,state.phase2),entry={roll,title:action.title,text:action.text,phase:state.phase2?'Segunda Fase':'Primera Fase'};state.aiHistory=[entry,...(Array.isArray(state.aiHistory)?state.aiHistory:[])].slice(0,8);saveState(state);render()}
const heading=Array.from(document.querySelectorAll('h2')).find(x=>x.textContent.includes('Control de partida'));if(heading){const box=document.createElement('div');box.id='varkhosCombatControl';box.className='varkhos-control';heading.after(box);render()}
const chalice=document.getElementById('chalice'),varkhos=document.getElementById('varkhos');chalice?.addEventListener('change',()=>{const state=getState();if(state.chaliceDestroyed!==chalice.checked)window.setVarkhosChalice(chalice.checked)});varkhos?.addEventListener('change',()=>{const state=getState();if(varkhos.checked&&state.current>0){state.current=0;saveState(state);render()}else if(!varkhos.checked&&state.current===0){state.current=1;saveState(state);render()}});
const originalReset=window.resetTest;if(typeof originalReset==='function')window.resetTest=function(){localStorage.removeItem(KEY);originalReset()};
if(!document.getElementById('varkhos-control-style')){const style=document.createElement('style');style.id='varkhos-control-style';style.textContent='.varkhos-control{margin:10px 0 18px;padding:13px;border:1px solid #922d39;border-radius:10px;background:linear-gradient(145deg,rgba(78,15,25,.48),rgba(15,10,9,.75))}.varkhos-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.varkhos-head b,.varkhos-head small{display:block}.varkhos-head b{font-size:1.35rem}.varkhos-head strong{color:#efc56d}.varkhos-wounds,.chalice-wounds{display:grid;grid-template-columns:1fr 1fr;margin:8px 0}.varkhos-wounds button,.chalice-wounds button{font-size:.75rem}.varkhos-phase,.varkhos-ai,.varkhos-chalice,.varkhos-seals{margin-top:9px;padding:9px;border:1px solid rgba(192,147,80,.35);border-radius:7px}.varkhos-phase b,.varkhos-phase span,.varkhos-phase small,.varkhos-chalice>span,.varkhos-chalice>small,.varkhos-seals>b,.varkhos-ai>b,.varkhos-ai-current span,.varkhos-ai-current small{display:block}.varkhos-phase span{margin:5px 0;color:#ead8b8}.varkhos-phase.phase-two{border-color:#c84343;background:rgba(120,18,24,.28)}.varkhos-ai>button{width:100%;margin:8px 0;padding:9px}.varkhos-ai-current{padding:9px;background:rgba(116,20,30,.3);border-left:3px solid #c05050}.varkhos-ai-current strong{color:#efc56d}.varkhos-ai-current span{margin:5px 0;font-size:.86rem}.varkhos-ai details{margin-top:8px;font-size:.78rem}.varkhos-ai details p{padding-bottom:6px;border-bottom:1px solid rgba(192,147,80,.2)}.varkhos-ai details small{display:block;color:#bd9c6a}.chalice-head{display:flex;justify-content:space-between;gap:8px;color:#d5ae69}.varkhos-chalice>span{margin:5px 0}.varkhos-chalice button{font-size:.66rem;padding:7px}.varkhos-chalice.chalice-broken{border-color:#d14b38;background:rgba(124,32,18,.24)}.chalice-impact{margin:8px 0;padding:8px;border:1px solid #b94732;color:#ffd08b;background:rgba(137,36,20,.35);font-size:.78rem;font-weight:bold}.varkhos-recovery{display:grid;grid-template-columns:1fr 1fr}.varkhos-last{color:#efc56d!important}.varkhos-seal{margin-top:5px;font-size:.78rem}.varkhos-seal.destroyed{color:#91c78a}.varkhos-seal.active{color:#e4a36e}.varkhos-defeated{margin-top:10px;text-align:center;padding:10px;background:#5f1018;color:#ffe0b0;font-weight:bold}@media(max-width:480px){.varkhos-head,.chalice-head{align-items:flex-start;flex-direction:column}.varkhos-wounds,.varkhos-recovery{grid-template-columns:1fr}}';document.head.appendChild(style)}
})();
