(function(){
const KEY='cruzadaAltarSigmar_mision5_html';
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function campaignHeroes(){try{return JSON.parse(localStorage.getItem('cruzadaCampaign')||'null')?.heroes||[]}catch(e){return[]}}
function usedHeroes(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}}
function saveUsed(used){localStorage.setItem(KEY,JSON.stringify(used))}
function renderAltar(){const box=document.getElementById('sigmarAltarControl');if(!box)return;const used=usedHeroes(),heroes=campaignHeroes(),available=heroes.filter(h=>!used[h.name]);if(!heroes.length){box.innerHTML='<p>No hay campaña activa.</p>';return}box.innerHTML='<b>☀ ACTIVAR ALTAR DE SIGMAR</b>'+(available.length?'<label>Héroe<select id="sigmarAltarHero">'+available.map(h=>'<option value="'+esc(h.name)+'">'+esc(h.name)+'</option>').join('')+'</select></label><div><button type="button" onclick="useSigmarAltar(\'heal\')">RECUPERAR 1 HERIDA</button><button type="button" onclick="useSigmarAltar(\'attack\')">+1 ATAQUE</button><button type="button" onclick="useSigmarAltar(\'save\')">SALVACIÓN ESPECIAL 5+</button></div>':'<p>Todos los héroes han utilizado ya el altar.</p>')+'<small>Usado: '+(Object.keys(used).length?Object.entries(used).map(([name,reward])=>esc(name)+' — '+esc(reward)).join(' · '):'ningún héroe')+'</small>'}
window.useSigmarAltar=function(choice){const select=document.getElementById('sigmarAltarHero');if(!select)return;const hero=select.value,used=usedHeroes();if(used[hero]){renderAltar();return}let reward='';if(choice==='heal'){const healed=window.healMissionHeroByName?.(hero,1)||0;if(!healed){alert('Este héroe no puede recuperar Heridas ahora. Elige otra recompensa o selecciona otro héroe.');return}reward='Recuperó 1 Herida'}else if(choice==='attack'){window.addMissionTemporaryEffect?.({hero,item:'Altar de Sigmar',label:'+1 Ataque',detail:'Duración: hasta el final de la misión',stat:'A',bonus:1});reward='+1 Ataque'}else{window.addMissionTemporaryEffect?.({hero,item:'Altar de Sigmar',label:'Salvación especial 5+',detail:'Duración: hasta el final del escenario',specialSave:5});reward='Salvación especial 5+'}used[hero]=reward;saveUsed(used);renderAltar();alert(hero+' recibe: '+reward+'.')}
const heading=Array.from(document.querySelectorAll('h3')).find(x=>x.textContent.trim()==='Altar de Sigmar');if(heading){const box=document.createElement('div');box.id='sigmarAltarControl';box.className='sigmar-altar-control';heading.nextElementSibling?.after(box);renderAltar()}
if(!document.getElementById('sigmar-altar-style')){const style=document.createElement('style');style.id='sigmar-altar-style';style.textContent='.sigmar-altar-control{margin:10px 0 18px;padding:11px;border:1px solid #a77a39;border-radius:8px;background:rgba(91,58,17,.25)}.sigmar-altar-control label,.sigmar-altar-control small{display:block;margin-top:8px}.sigmar-altar-control select{width:100%;margin-top:5px;padding:9px;background:#17110e;color:#eee;border:1px solid #765e35;border-radius:6px}.sigmar-altar-control button{font-size:.72rem;padding:8px;margin:3px}';document.head.appendChild(style)}
})();
