(function(){
const KEY='cruzadaVarkhos_mision5_html';
function mission4(){try{return JSON.parse(localStorage.getItem('cruzadaMission4')||'{}')}catch(e){return{}}}
function seals(){const m=mission4();return{blood:!!m.blood,bone:!!m.bone,shadow:!!m.shadow}}
function initialState(){const s=seals(),max=6+(s.blood?0:1);return{current:max,max,chaliceDestroyed:!!document.getElementById('chalice')?.checked,phase2:false,lastRegen:null}}
function getState(){let value;try{value=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){}const fresh=initialState();if(!value)value=fresh;value.max=fresh.max;value.current=Math.max(0,Math.min(value.max,Number(value.current)??value.max));value.chaliceDestroyed=!!value.chaliceDestroyed;value.phase2=!!value.phase2||value.chaliceDestroyed||value.current<=3;return value}
function saveState(value){localStorage.setItem(KEY,JSON.stringify(value))}
function syncMissionCheckbox(id,checked){const input=document.getElementById(id);if(!input||input.checked===checked)return;input.checked=checked;input.dispatchEvent(new Event('change',{bubbles:true}))}
function sealLine(destroyed,yes,no){return '<div class="varkhos-seal '+(destroyed?'destroyed':'active')+'">'+(destroyed?'✓ '+yes:'⚠ '+no)+'</div>'}
function render(){const box=document.getElementById('varkhosCombatControl');if(!box)return;const state=getState(),s=seals(),phase2=state.phase2,dead=state.current<=0;saveState(state);syncMissionCheckbox('varkhos',dead);syncMissionCheckbox('chalice',state.chaliceDestroyed);box.innerHTML='<div class="varkhos-head"><div><small>JEFE FINAL</small><b>VARKHOS</b></div><strong>'+state.current+' / '+state.max+' HERIDAS</strong></div><div class="varkhos-wounds"><button type="button" onclick="changeVarkhosWounds(-1)" '+(dead?'disabled':'')+'>− HERIDA</button><button type="button" onclick="changeVarkhosWounds(1)" '+(state.current>=state.max?'disabled':'')+'>+ HERIDA</button></div><div class="varkhos-phase '+(phase2?'phase-two':'')+'"><b>'+(phase2?'SEGUNDA FASE · LA BESTIA CARMESÍ':'PRIMERA FASE · EL NOBLE INMORTAL')+'</b><span>FUE '+(phase2?6:5)+' · ATQ '+(phase2?4:3)+' · R 5 · Salvación 4+</span><small>'+(phase2?'Provoca Terror · Mirada Hipnótica desactivada · +1 FUE y +1 ATQ':'Magia completa · Mirada Hipnótica disponible')+'</small></div><div class="varkhos-chalice"><label><input type="checkbox" id="varkhosChaliceToggle" '+(state.chaliceDestroyed?'checked':'')+' onchange="setVarkhosChalice(this.checked)"> Cáliz de Sangre Negra destruido</label><small>'+(state.chaliceDestroyed?'Sin Regeneración ni recuperación de Heridas.':'Regeneración 6+ y recupera 1 Herida al inicio del turno del Máster.')+'</small><div><button type="button" onclick="rollVarkhosRegeneration()" '+(state.chaliceDestroyed||dead||state.current>=state.max?'disabled':'')+'>TIRAR REGENERACIÓN 6+</button><button type="button" onclick="healVarkhosAtMasterTurn()" '+(state.chaliceDestroyed||dead||state.current>=state.max?'disabled':'')+'>INICIO TURNO DEL MÁSTER · +1 H</button></div>'+(state.lastRegen?'<small class="varkhos-last">Última regeneración: '+state.lastRegen+'</small>':'')+'</div><div class="varkhos-seals"><b>CONSECUENCIAS DE LOS SELLOS</b>'+sealLine(s.blood,'Sello de Sangre destruido','Sello de Sangre activo: +1 Herida máxima')+sealLine(s.bone,'Sello de Hueso destruido','Sello de Hueso activo: coloca 2 Esqueletos adicionales')+sealLine(s.shadow,'Sello de las Sombras destruido','Sello de las Sombras activo: cobertura ligera permanente')+'</div>'+(dead?'<div class="varkhos-defeated">☠ VARKHOS HA SIDO DERROTADO</div>':'')}
window.changeVarkhosWounds=function(delta){const state=getState();state.current=Math.max(0,Math.min(state.max,state.current+delta));if(state.current<=3)state.phase2=true;saveState(state);render()}
window.setVarkhosChalice=function(destroyed){const state=getState();state.chaliceDestroyed=!!destroyed;if(destroyed)state.phase2=true;saveState(state);render()}
window.rollVarkhosRegeneration=function(){const state=getState();if(state.chaliceDestroyed||state.current<=0||state.current>=state.max)return;const roll=1+Math.floor(Math.random()*6);if(roll===6)state.current++;state.lastRegen=roll+(roll===6?' · Éxito, recupera 1 Herida':' · Fallo');saveState(state);render();alert('Regeneración de Varkhos: '+state.lastRegen+'.')}
window.healVarkhosAtMasterTurn=function(){const state=getState();if(state.chaliceDestroyed||state.current<=0||state.current>=state.max)return;state.current++;saveState(state);render()}
const heading=Array.from(document.querySelectorAll('h2')).find(x=>x.textContent.includes('Control de partida'));if(heading){const box=document.createElement('div');box.id='varkhosCombatControl';box.className='varkhos-control';heading.after(box);render()}
const chalice=document.getElementById('chalice'),varkhos=document.getElementById('varkhos');chalice?.addEventListener('change',()=>{const state=getState();if(state.chaliceDestroyed!==chalice.checked)window.setVarkhosChalice(chalice.checked)});varkhos?.addEventListener('change',()=>{const state=getState();if(varkhos.checked&&state.current>0){state.current=0;saveState(state);render()}else if(!varkhos.checked&&state.current===0){state.current=1;saveState(state);render()}});
const originalReset=window.resetTest;if(typeof originalReset==='function')window.resetTest=function(){localStorage.removeItem(KEY);originalReset()};
if(!document.getElementById('varkhos-control-style')){const style=document.createElement('style');style.id='varkhos-control-style';style.textContent='.varkhos-control{margin:10px 0 18px;padding:13px;border:1px solid #922d39;border-radius:10px;background:linear-gradient(145deg,rgba(78,15,25,.48),rgba(15,10,9,.75))}.varkhos-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.varkhos-head b,.varkhos-head small{display:block}.varkhos-head b{font-size:1.35rem}.varkhos-head strong{color:#efc56d}.varkhos-wounds{display:grid;grid-template-columns:1fr 1fr;margin:8px 0}.varkhos-wounds button{font-size:.75rem}.varkhos-phase,.varkhos-chalice,.varkhos-seals{margin-top:9px;padding:9px;border:1px solid rgba(192,147,80,.35);border-radius:7px}.varkhos-phase b,.varkhos-phase span,.varkhos-phase small,.varkhos-chalice small,.varkhos-seals>b{display:block}.varkhos-phase span{margin:5px 0;color:#ead8b8}.varkhos-phase.phase-two{border-color:#c84343;background:rgba(120,18,24,.28)}.varkhos-chalice label{padding:0}.varkhos-chalice button{font-size:.66rem;padding:7px}.varkhos-last{color:#efc56d!important}.varkhos-seal{margin-top:5px;font-size:.78rem}.varkhos-seal.destroyed{color:#91c78a}.varkhos-seal.active{color:#e4a36e}.varkhos-defeated{margin-top:10px;text-align:center;padding:10px;background:#5f1018;color:#ffe0b0;font-weight:bold}@media(max-width:480px){.varkhos-head{align-items:flex-start;flex-direction:column}.varkhos-wounds{grid-template-columns:1fr}}';document.head.appendChild(style)}
})();
